  job:
    include:
      - stage: test
        name: "Test operation"
        language: node_js
        node_js: "stable"
      - stage: Notification
        name: "Notify results"
        notifications:
          email:
            if: branch = master
            recipients:
              - alfredo.rivas@softtek.com
            on_success: always
            on_failure: always