  job:
    include:
      - stage: install
        name: "Intall Rake"
        script: gem install rake
      - stage: test
        name: "Test operation"
        language: node_js
        node_js: "stable"
      - stage: Notification
        name: "Notify results"
notifications:
  email:
    - alfredo.rivas@softtek.com