  job:
    include:
      - stage: install
        name: "Intall Rake"
        script: gem install rake
      - stage: test
        name: "Test operation"
        language: node_js
        node_js: "stable"
      - stage: Notification
        name: "Notify results"
        script: "Notify"

notifications:
  email:
    recipients:
      - alfredo.rivas@softtek.com
    on_success: always # default: change
    on_failure: always # default: always